### ISSUE TITLE
Rich Text Issue

### ISSUE THREAD

**Issue by DidierBailly** [openlowcode/Open-Lowcode#101]
Even with none of rich text features, Parasits signs are coming.

Can't give a schema to reproduce.

The ']' are parasites. Impossible to get rid of them

**Comment by openlowcode** [comment]
Hi Didier, working on it.

**Comment by openlowcode** [comment]
It seems this is linked to the following:
- bad treatment of entered or imported text with, in some cases, the opening bracket not escaped.
- weirdly, when generating the text in the widget, some closing bracket 'spill' on the text payload.

Example below of content in the database of a faulty rich text field.

`[]Ceci est un test avec un [[ dans le texte ]
[][]]]Ceci est un test avec un [[ dans
[][]]]Ceci est un test avec un [[ dans le texte ]
[][]]]
[][]]] `
