### ISSUE TITLE
Duplicate code for StringFormatter

### ISSUE THREAD

**Issue by nicolasdemauroy** [openlowcode/Open-Lowcode#196]
There is a duplicate package for StringFormatter and SourgeGenerator. They are available in the two following paths:

- org.openlowcode.design.generation
- org.openlowcode.tools.file

This duplication of paths should be suppressed, keeping the most used package (or the tools package if the APIs needs to be accessed only from design).

**Comment by openlowcode** [comment]
Proposal is to suppress the two classes in the package org.openlowcode.tools.file. Only use is StringFormatter from GenericLinkDefinition. Proposal is to add a proper description for a generic link.
