### ISSUE TITLE
MultiDimensionChild : when creating new versions of object, new children according to multi-dimension children are not created.

### ISSUE THREAD

**Issue by nicolasdemauroy** [openlowcode/Open-Lowcode#205]
How to reproduce:
- create an object, it gets correct multi-dimension children (say from year to year +5)
- up-issue the object, changing year in the process, existing children are copied (correct) but new children (year+1 ... +5) are not created.
- when creating a new object with the new year, however, it works.

**Comment by openlowcode** [comment]
This is not a defect of the  property. This error happened in a hierarchy of objects:

- Budget Round: the parent of all activities
- Activity : one line of data with property HasMultiDimensionChild
- Allocated the children with property MultiDimensionChild

The items for allocated are determined by a field in the budget round. The budget round was up-issued with a custom action that also created new versions for activity. However, the parent budget round has to be changed. This is done with the following code:

```
	Activity[] newroundactivities = Activity.revise(oldroundactivities,(a)->a.setparentwithoutupdateforplan(newplan.getId()));
```
