### ISSUE TITLE
What's the default user and password

### ISSUE THREAD

**Issue by lvxingtu** [openlowcode/Open-Lowcode#276]
I'm in the login page and don't know what next do.
I study the wiki a lot of times can't find anything about username and password in Login page

**Comment by lvxingtu** [comment]
I find it. It's admin.

**Comment by openlowcode** [comment]
Hi @lvxingtu , thanks for trying Open Lowcode. I now documented in the [FAQ](https://github.com/openlowcode/Open-Lowcode/wiki/Frequently-Asked-Questions) the default passwords. Feel free to ask any questions about the software through this [contact form](https://openlowcode.com/contact/).
